fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_library",
            "create_organization",
            "rename_organization",
            "delete_organization",
            "create_topic",
            "rename_topic",
            "delete_topic",
            "create_meeting_group",
            "rename_meeting_group",
            "delete_meeting_group",
            "list_artifacts",
            "get_artifact",
            "import_audio",
            "import_transcript",
            "rename_artifact",
            "delete_artifact",
            "get_artifact_audio_path",
            "set_openai_api_key",
            "clear_openai_api_key",
            "openai_api_key_configured",
            "chat_scope_preview",
            "get_chat_thread",
            "new_chat_thread",
            "ask_chat",
        ]),
    ))
    .expect("tauri build failed");
}
